### ISSUE TITLE
Crash during aggregation

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris-autoprocess#22]
```
Task id: e2cf807e-5756-4a2c-94f2-b7327c5d65d8

Traceback (most recent call last):
  File "/opt/enhydris-openhi/venv/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/enhydris-openhi/venv/lib/python3.5/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/enhydris-openhi/enhydris_autoprocess/tasks.py", line 8, in execute_auto_process
    AutoProcess.objects.get(id=auto_process_id).execute()
  File "/opt/enhydris-openhi/enhydris_autoprocess/models.py", line 34, in execute
    result = self.process_timeseries()
  File "/opt/enhydris-openhi/enhydris_autoprocess/models.py", line 42, in process_timeseries
    return childobj.process_timeseries()
  File "/opt/enhydris-openhi/enhydris_autoprocess/models.py", line 217, in process_timeseries
    self._aggregate_time_series()
  File "/opt/enhydris-openhi/enhydris_autoprocess/models.py", line 232, in _aggregate_time_series
    target_timestamp_offset=self.resulting_timestamp_offset or None,
  File "/opt/enhydris-openhi/venv/lib/python3.5/site-packages/haggregate/haggregate.py", line 80, in aggregate
    while pd.isnull(result.data["value"]).iloc[0]:
  File "/opt/enhydris-openhi/venv/lib/python3.5/site-packages/pandas/core/indexing.py", line 1500, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/opt/enhydris-openhi/venv/lib/python3.5/site-packages/pandas/core/indexing.py", line 2230, in _getitem_axis
    self._validate_integer(key, axis)
  File "/opt/enhydris-openhi/venv/lib/python3.5/site-packages/pandas/core/indexing.py", line 2139, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

**Comment by aptiko** [comment]
This is a haggregate bug, openmeteo/haggregate#14.
