### ISSUE TITLE
Timeseries matching query does not exist

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris-autoprocess#52]
```
Traceback (most recent call last):
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
enhydris.models.Timeseries.DoesNotExist: Timeseries matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "only_one_raw_or_processed_timeseries_per_group"
DETAIL:  Key (timeseries_group_id)=(814) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/enhydris-openhi/enhydris_autoprocess/tasks.py", line 8, in execute_auto_process
    AutoProcess.objects.get(id=auto_process_id).as_specific_instance.execute()
  File "/opt/enhydris-openhi/enhydris_autoprocess/models.py", line 27, in execute
    result = self.process_timeseries()
  File "/opt/enhydris-openhi/enhydris_autoprocess/models.py", line 307, in process_timeseries
    timeseries = self.htimeseries.data
  File "/opt/enhydris-openhi/enhydris_autoprocess/models.py", line 34, in htimeseries
    start_date=self._get_start_date()
  File "/opt/enhydris-openhi/enhydris_autoprocess/models.py", line 59, in _get_start_date
    start_date = self.target_timeseries.end_date
  File "/opt/enhydris-openhi/enhydris_autoprocess/models.py", line 302, in target_timeseries
    type=Timeseries.PROCESSED
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 674, in get_or_create
    return super(RelatedManager, self.db_manager(db)).get_or_create(**kwargs)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/models/query.py", line 541, in get_or_create
    return self._create_object_from_params(kwargs, params)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/models/query.py", line 583, in _create_object_from_params
    raise e
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/models/query.py", line 575, in _create_object_from_params
    obj = self.create(**params)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/enhydris-openhi/enhydris/models.py", line 833, in save
    super(Timeseries, self).save(force_insert, force_update, *args, **kwargs)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "only_one_raw_or_processed_timeseries_per_group"
DETAIL:  Key (timeseries_group_id)=(814) already exists.
```

**Comment by aptiko** [comment]
After the recent changes (#56 and openmeteo/enhydris#407), it is possible that this bug is no more. Closing. We'll only investigate further if it comes up again.
