### ISSUE TITLE
Error during rate-of-change check

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris-autoprocess#54]
```
Traceback (most recent call last):
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/enhydris-openmeteo/enhydris_autoprocess/tasks.py", line 8, in execute_auto_process
    AutoProcess.objects.get(id=auto_process_id).as_specific_instance.execute()
  File "/opt/enhydris-openmeteo/enhydris_autoprocess/models.py", line 27, in execute
    result = self.process_timeseries()
  File "/opt/enhydris-openmeteo/enhydris_autoprocess/models.py", line 116, in process_timeseries
    checked_timeseries = check.check_timeseries(checked_timeseries)
  File "/opt/enhydris-openmeteo/enhydris_autoprocess/models.py", line 215, in check_timeseries
    flag="TEMPORAL",
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/rocc/rocc.py", line 9, in rocc
    Rocc(timeseries, thresholds, symmetric, flag).execute()
  File "rocc/calculation.pyx", line 20, in rocc.calculation.Rocc.execute
  File "rocc/calculation.pyx", line 41, in rocc.calculation.Rocc._transform_to_plain_numpy
ValueError: max() arg is an empty sequence
```

**Comment by aptiko** [comment]
This is a rocc problem, not an enhydris-autoprocess problem. rocc#2
