### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris-autoprocess#59]
In Celery worker:
```
Traceback (most recent call last):
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/enhydris-openhi/enhydris_autoprocess/tasks.py", line 8, in execute_auto_process
    AutoProcess.objects.get(id=auto_process_id).as_specific_instance.execute()
  File "/opt/enhydris-openhi/enhydris_autoprocess/models.py", line 29, in execute
    result = self.process_timeseries()
  File "/opt/enhydris-openhi/enhydris_autoprocess/models.py", line 118, in process_timeseries
    checked_timeseries = check.check_timeseries(checked_timeseries)
  File "/opt/enhydris-openhi/enhydris_autoprocess/models.py", line 217, in check_timeseries
    flag="TEMPORAL",
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/rocc/rocc.py", line 9, in rocc
    Rocc(timeseries, thresholds, symmetric, flag).execute()
  File "rocc/calculation.pyx", line 20, in rocc.calculation.Rocc.execute
  File "rocc/calculation.pyx", line 41, in rocc.calculation.Rocc._transform_to_plain_numpy
ValueError: max() arg is an empty sequence
```

**Comment by aptiko** [comment]
This looks like a duplicate of openmeteo/rocc#2, which was fixed on 29 December. Go figure why this ticket was submitted in 10 February. Maybe rocc 2.0 hadn't been installed yet, or maybe Celery hadn't been restarted. Closing.
