### ISSUE TITLE
IntegrityError: duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris-autoprocess#63]
During celery task:

```
Traceback (most recent call last):
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/enhydris-openmeteo/enhydris_autoprocess/tasks.py", line 8, in execute_auto_process
    AutoProcess.objects.get(id=auto_process_id).as_specific_instance.execute()
  File "/opt/enhydris-openmeteo/enhydris_autoprocess/models.py", line 30, in execute
    self.target_timeseries.append_data(result)
  File "/opt/enhydris-openmeteo/enhydris/models.py", line 777, in append_data
    result = TimeseriesRecord.bulk_insert(self, ahtimeseries)
  File "/opt/enhydris-openmeteo/enhydris/models.py", line 892, in bulk_insert
    cls.objects.bulk_create(batch, batch_size)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/db/models/query.py", line 468, in bulk_create
    self._batched_insert(objs_with_pk, fields, batch_size, ignore_conflicts=ignore_conflicts)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1204, in _batched_insert
    ignore_conflicts=ignore_conflicts,
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "29_57_enhydris_timeseriesrecord_pk"
DETAIL:  Key (timeseries_id, "timestamp")=(10198, 2021-04-15 03:20:00+00) already exists.
```

**Comment by aptiko** [comment]
The is probably a user error - specified a raw time series (wind speed) as a target time series for processing. It went away after a few hours and we know the user was working on the station in these days. Resolving as wontfix.
